site_name: AGL Framework Binder
theme: readthedocs
docs_dir: docs
pages:
  - 'Overview' : 'index.md'
  - 'How to write a binding ?': 'afb-binding-writing.md'
  - 'Binding references': 'afb-binding-references.md'
  - 'Migration from v1 to v2' : 'afb-migration-v1-to-v2.md'
  - 'Binder events guide' : 'afb-events-guide.md'
  - 'Binder Application writing guide' : 'afb-application-writing.md'
  - 'Binder daemon vocabulary' : 'afb-daemon-vocabulary.md'
  - 'Annexes':
    - 'Installing the binder on a desktop': 'afb-desktop-package.md'
    - 'Options of afb-daemon' : 'afb-daemon-options.md'

