site_name: AGL Framework Binder
theme: readthedocs
docs_dir: docs
# tr '*])([' "-''''" < docs/SUMMARY.md | sed "s/^\(.*'\)'/  \1: '/"
pages:
  - 'Overview' : 'index.md'
  - 'Binder Overview': 'afb-introduction.md'
  - 'Binder daemon vocabulary': 'afb-daemon-vocabulary.md'
  - 'How to write a binding ?': 'afb-binding-writing.md'
  - 'Binding references':
    - 'Types and globals': 'reference-v3/types-and-globals.md'
    - 'Functions of class afb_api': 'reference-v3/func-api.md'
    - 'Functions of class afb_req': 'reference-v3/func-req.md'
    - 'Functions of class afb_event': 'reference-v3/func-event.md'
    - 'Functions of class afb_daemon': 'reference-v3/func-daemon.md'
    - 'Functions of class afb_service': 'reference-v3/func-service.md'
    - 'Macros for logging': 'reference-v3/macro-log.md'
  - 'Binder events guide': 'afb-events-guide.md'
  - 'Binder Application writing guide': 'afb-application-writing.md'
  - 'Annexes': 
    - 'Migration to binding v3': 'afb-migration-to-binding-v3.md'
    - 'WebSocket protocol x-afb-ws-json1': 'protocol-x-afb-ws-json1.md'
    - 'Installing the binder on a desktop': 'afb-desktop-package.md'
    - 'Options of afb-daemon': 'afb-daemon-options.md'
    - 'Debugging binder and bindings': 'afb-daemon-debugging.md'
    - 'LEGACY Guide to migrate bindings from v1 to v2': 'legacy/afb-migration-v1-to-v2.md'
    - 'LEGACY Binding V2 references': 'legacy/afb-binding-v2-references.md'
  - 'Document revisions': 'REVISIONS.md'

